### ISSUE TITLE
How is this going?There are numerous loading on the webpage

### ISSUE THREAD

**Issue by hjq1001** [Midnight-Lizard/Midnight-Lizard#126] opened 2018-06-11 18:03 UTC
How is this going?There are numerous loading on the webpage

**Comment by hjq1001** [comment] 2018-06-11 18:05
![image](https://user-images.githubusercontent.com/35657236/41248903-fa46d516-6de4-11e8-85bb-39346e683777.png)

**Comment by pavel-agarkov** [comment] 2018-06-11 18:20
It is a known issue.
I cannot reproduce it on the website you've mentioned, but a common solution should help:
Remove all limits from background (fond) images:
![image](https://user-images.githubusercontent.com/24639631/41249562-1f184956-6dbd-11e8-9f35-a8b709c65b27.png)

**Comment by hjq1001** [comment] 2018-06-12 03:55
Thank you, your method is very effective!

**Comment by pavel-agarkov** [comment] 2018-06-12 06:40
Closing it by now, but will try to fix properly in the future.

**Closed by pavel-agarkov** 2018-06-12 06:40 UTC
