### ISSUE TITLE
Make Midnight Lizard able to use your location to determine when to turn on and off

### ISSUE THREAD

**Issue by fighuass** [Midnight-Lizard/Midnight-Lizard#243] opened 2019-09-28 18:04 UTC
Currently you have to manually set the times for when ML will turn on and off automatically, it would be better if it gave you the option to use your location to automatically determine when to do so by looking at sunset and sunrise times.

**Comment by pavel-agarkov** [comment] 2019-09-28 21:41
duplicate of #178

**Closed by pavel-agarkov** 2019-09-28 21:41 UTC
Labels: duplicate
