### ISSUE TITLE
Quora's Answer Composition Box BG Not Changing

### ISSUE THREAD

**Issue by Koolstr** [Midnight-Lizard/Midnight-Lizard#136] opened 2018-07-06 05:07 UTC
I am running a full-black/dark theme, yet when I click on the 'Answer Question' button on a Quora.com question, the text box shown does not have its background themed. I've included a picture for reference. Oddly, the text I put in the text box does get themed, showing in my light hacker green, making the text practically invisible against the white background.

I've noticed this phenomenon on multiple sites actually, so it is not exclusive to Quora. Please resolve this for a more consistent and pleasant experience with your extension. It's troubling to work with arbitrary blocks of white showing up on pages, and I feel they are all connected to the same bug. If you resolve one, you'd probably resolve them all in the process.

![2018-07-06 01_06_49-what is your favorite song and why_ - quora](https://user-images.githubusercontent.com/2044760/42360783-eabc0198-80b8-11e8-9459-9745bada486a.png)

**Comment by pavel-agarkov** [comment] 2018-07-06 07:15
This case is not a Midnight Lizard's bug.
The problem is that quora does fight with Midnight Lizard and constantly changes background back to white.
It was causing infinite loop and crashing browser so I added this text block into ignore list a long time ago.
Today's Midnight Lizard is much smarter and wouldn't crash even without ignoring this block, but it still cannot win the fight (since it is smarter it gives up after a few rounds).
I've just implemented a workaround for this concrete text block which manually sets a background color with high precedence and wins without fight:
![image](https://user-images.githubusercontent.com/24639631/42364711-d5851f7a-8104-11e8-8d5d-eca47d2c5bb8.png)
But it will fix just this problem and won't anything else. I will publish an update soon.
Closing the issue by now.
If you would have any other examples please add a comment here or create a new issue.
Thank you.

**Comment by Koolstr** [comment] 2018-07-06 07:33
I am impressed with the immediate response and resolution :D 
Thank you for fixing this. Even if it is a janky, forced, singular solution, it's better to have it, I think. I'll probably come back to this thread to notify you of other white background anomalies in the future.

**Comment by Koolstr** [comment] 2018-07-13 07:45
Found another. On the Google Play Store, play.google.com, if I click on the 'Install' button for an app, the resulting popup for device selection has a white background. Please override this one as well.

**Comment by pavel-agarkov** [comment] 2018-07-13 12:10
This is a Firefox bug. Sometimes Firefox does not compute styles at all.
I have a workaround for this bug - if Firefox does not know what color is used - I assume it is transparent.
It works somehow most of the times - but not for this case since in reality it is not transparent but white.

**Closed by pavel-agarkov** 2018-07-13 12:10 UTC

**Comment by Koolstr** [comment] 2018-07-13 15:42
Sooo....nothing can be done about this one?
