### ISSUE TITLE
[Bug?] When javascript is not enabled on some sites, color scheme doesn't apply to foreground area automatically

### ISSUE THREAD

**Issue by Retia-Adolf** [Midnight-Lizard/Midnight-Lizard#156] opened 2018-08-17 13:25 UTC
## Example color scheme not apply
https://www.wikihow.com/wikiHow:Creative-Commons

![](https://screenshotscdn.firefoxusercontent.com/images/246cd010-66a1-4699-99be-0bac510752fa.png)

Pic 1: White area keeps there whatever times I refresh the page.

![](https://screenshotscdn.firefoxusercontent.com/images/cb011727-9729-443e-8b2f-2e24966b3a43.png)

Pic 2: Turn off Midnight Lizard for current site and Turn it on again, color scheme fully applied. But once refresh page, previous effort does not work.

## Example no problem when javascript disabled
http://www.funretrospectives.com/is-is-not-does-does-not/

![](https://screenshotscdn.firefoxusercontent.com/images/665ae639-c65e-4e33-82fc-a2c58506d047.png)

**Comment by pavel-agarkov** [comment] 2018-08-17 13:36
Cannot reproduce the issue.
For me both pages works in both Chrome and Firefox with or without JavaScript all the time.
Can you think about something that can further clarify your case?

**Comment by Retia-Adolf** [comment] 2018-08-17 14:49
@pavel-agarkov 

Common > Processing Mode set to Complex mode

Color scheme: Dimmed Dust

Midnight Lizard is latest version.

Firefox Developer Edition 62.0b17 (64-bit)

Used Firefox's Developer Tools > Settings > Advanced Settings > Disable JavaScript to disable.

BTW I have a lots of extensions installed, but anyway the issue presents only when JavaScript disabled.

**Comment by pavel-agarkov** [comment] 2018-08-17 16:31
Still no problems with exactly the same setup.
I used to have similar problem on Chrome and it looked like Chrome also disabled extension javascript as well but partially... So it might be a browser bug.
Closing it for now.

**Closed by pavel-agarkov** 2018-08-17 16:31 UTC
