### ISSUE TITLE
Editing/Deleting Custom Themes has no effect

### ISSUE THREAD

**Issue by BreadYogurt** [Midnight-Lizard/Midnight-Lizard#127] opened 2018-06-12 03:56 UTC
Not sure if I'm doing it right because the UI is confusing, but attempting to update or delete a custom theme does not do anything. I'm using Firefox.

**Comment by pavel-agarkov** [comment] 2018-06-12 06:50
Please describe what you are doing step by step.
If you are confused with absence of some message boxes - I removed some of them since they were destructive, but everything works as designed.
When you (update/delete) any theme it gets immediately (updated/reverted to default) on the page where it is used even if it is not the current page.

**Comment by pavel-agarkov** [comment] 2018-06-12 06:54
And a deleted color scheme stays applied on the popup so you still can save/apply/export it before closing the popup.

**Comment by pavel-agarkov** [comment] 2018-06-13 20:55
Please reopen this issue if problem is still relevant.
Thank you.

**Closed by pavel-agarkov** 2018-06-13 20:55 UTC
